spring.application.name=t1project
spring.datasource.username=postgres
spring.datasource.password=asdf56y
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.consumer.auto-offset-reset=latest

metric.time.limit.ms=1000
cache.ttl.seconds=30

client.rejected-transaction-limit=2

spring.datasource.url=jdbc:postgresql://db:5432/mydb
spring.kafka.bootstrap-servers=kafka:9092

unblocking.scheduler.client.fixedRate=30000
unblocking.scheduler.account.fixedRate=30000


management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.metrics.enabled=true